vim.keymap.set("n", "<leader>v", vim.cmd.Vex)
vim.keymap.set("n", "<leader>s", vim.cmd.Sex)
vim.keymap.set("n", "<leader>e", vim.cmd.Ex)
vim.keymap.set("n", "<leader>qa", function()
  vim.cmd("qa!")
end)
vim.keymap.set("n", "<leader>q", function()
  vim.cmd("q!")
end)
vim.keymap.set("n", "<leader>w", function()
  vim.cmd("w!")
  print("Saved!")
end)

-- Toggle diagnostics
vim.keymap.set("n", "<leader>td", function()
  vim.diagnostic.enable(not vim.diagnostic.is_enabled())
end)
